### PR TITLE
[CSBS] Fix issue with creating `csbs_backup`

### LINKED ISSUE #1358: [CSBS] Issues with SDK in backup resource
```
Error: Error waiting for Backup to become available: json: cannot unmarshal number 25.2 into Go struct field .checkpoint_item of type int
```

# Affected Resource(s)
`resource/opentelekomcloud_csbs_backup_policy_v1`

### PR DESCRIPTION
**Pull request by lego963**
## Summary of the Pull Request
Fix issue with creating `resource/opentelekomcloud_csbs_backup_v1`
Fixes: #1358

## PR Checklist

* [x] Refers to: #1358
* [x] Tests added/passed.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccCSBSBackupPolicyV1DataSource_basic
--- PASS: TestAccCSBSBackupPolicyV1DataSource_basic (193.85s)
=== RUN   TestAccCSBSBackupV1DataSource_basic
--- PASS: TestAccCSBSBackupV1DataSource_basic (696.34s)
=== RUN   TestAccCSBSBackupPolicyV1_importWeekMonth
--- PASS: TestAccCSBSBackupPolicyV1_importWeekMonth (200.07s)
=== RUN   TestAccCSBSBackupV1_importBasic
--- PASS: TestAccCSBSBackupV1_importBasic (766.75s)
=== RUN   TestAccCSBSBackupPolicyV1_basic
--- PASS: TestAccCSBSBackupPolicyV1_basic (265.08s)
=== RUN   TestAccCSBSBackupPolicyV1_timeout
--- PASS: TestAccCSBSBackupPolicyV1_timeout (174.03s)
=== RUN   TestAccCSBSBackupPolicyV1_weekMonth
--- PASS: TestAccCSBSBackupPolicyV1_weekMonth (176.72s)
=== RUN   TestAccCSBSBackupV1_basic
--- PASS: TestAccCSBSBackupV1_basic (745.50s)
=== RUN   TestAccCSBSBackupV1_timeout
--- PASS: TestAccCSBSBackupV1_timeout (688.18s)
PASS
ok  	github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/acceptance/csbs	3909.361s

Process finished with the exit code 0

```

### CODE REVIEW

**Review by outcatcher — DISMISSED** [review]

**Review by outcatcher — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by lego963** [comment]
regate

**Comment by lego963** [comment]
regate

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by lego963** [comment]
regate

**Comment by lego963** [comment]
recheck

**Pull request merged**
