### PR TITLE
Some parameters should be computed as they are optional

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by niuzhenguo** [comment]
@mcanevet why does parameters should be computed as they are optional? Value of the parameters can either comes from the config, is computed, or is both.

**Comment by mcanevet** [comment]
If I don't set it it is not idempotent if it not computed.

**Comment by niuzhenguo** [comment]
@zengchen1024 can you please help to check such optional ELB parameters?

**Pull request merged**
