### PR TITLE
Use lib of golangsdk for dns service

### PR DESCRIPTION
**Pull request by zengchen1024**
This pr changed the dependent lib of DNS service to golangsdk, because there is a slight difference between the lib of  golangsdk and gophercloud on DNS service.

this pr is based on #9  #10

### CODE REVIEW

**Comment by zengchen1024** [comment]
@cgriggs01 Could you please merge this pr? Thanks very much!

**Comment by zengchen1024** [comment]
@paultyng Cloud you take a look at this pr? Thanks!

**Comment by paultyng** [comment]
@zengchen1024 do you mind posting the acc test results in the PR as I can't run them internally? Just a snippet of the relevant log output is fine ([like this](https://github.com/terraform-providers/terraform-provider-azurerm/pull/950#issue-173525714)).

**Comment by zengchen1024** [comment]
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2RecordSet_basic -timeout 240m
=== RUN   TestAccDNSV2RecordSet_basic
--- PASS: TestAccDNSV2RecordSet_basic (156.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     156.917s

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2RecordSet_readTTL -timeout 240m
=== RUN   TestAccDNSV2RecordSet_readTTL
--- PASS: TestAccDNSV2RecordSet_readTTL (712.83s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     712.836s

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2RecordSet_timeout -timeout 240m
=== RUN   TestAccDNSV2RecordSet_timeout
--- PASS: TestAccDNSV2RecordSet_timeout (123.57s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     123.574s

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2Zone_basic -timeout 240m
=== RUN   TestAccDNSV2Zone_basic
--- PASS: TestAccDNSV2Zone_basic (126.32s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     126.328s

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2Zone_readTTL -timeout 240m
=== RUN   TestAccDNSV2Zone_readTTL
--- PASS: TestAccDNSV2Zone_readTTL (177.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     177.914s

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccDNSV2Zone_timeout -timeout 240m
=== RUN   TestAccDNSV2Zone_timeout
--- PASS: TestAccDNSV2Zone_timeout (180.68s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     180.684s
```

**Comment by zengchen1024** [comment]
@paultyng Really appreciate your help! Thanks!

**Comment by paultyng** [comment]
Merged in #17

**Pull request closed without merging**
