### PR TITLE
[DCS] Change Capacity from int to float32

### PR DESCRIPTION
**Pull request by Aloento**
## Summary of the Pull Request

Change Capacity from int to float32

## PR Checklist

* [x] Refers to: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1839
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
```

### CODE REVIEW

**Comment by anton-sidelnikov** [comment]
@Aloento please update go.mod properly, use go get url@v0.5.19, and add test with float value

**Review by artem-lifshits — CHANGES_REQUESTED** [review]
Please add the new test to run 0.125 capacity as made in gopher.
If you still don't have access for test run just make the changes and I'll do the run from my side.

**Comment by Aloento** [comment]
@artem-lifshits could you redo the test? Now it's should be fine. we don't need to change the sdk.

**Comment by vladimirvshivkov** [comment]
please update golangsdk to v0.5.20

**Comment by vladimirvshivkov** [comment]
@Aloento,
checkout your commits into branch of this [project ](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud) to merge  to avoid failing `
labeler / triage (pull_request)` check , please.
then recreate PR

**Comment by Aloento** [comment]
https://github.com/opentelekomcloud/gophertelekomcloud/pull/380

**Pull request closed without merging**
