### PR TITLE
Fix vendor status of aws

### PR DESCRIPTION
**Pull request by zengchen1024**
run 'govendor sync' to update the lib of aws, which will update the directory of 'vendor/github.com/aws/aws-sdk-go/'

for issue #35 

this pr depends on #32

### CODE REVIEW

**Comment by zengchen1024** [comment]
all acceptance test cases are passed. see http://paste.openstack.org/show/716977/

**Comment by niuzhenguo** [comment]
why this also contains the commit "fix acc test of TestAccS3Bucket_logging" which is in another PR? you should checkout this branch from master, otherwise some collisions will happen if this one get merged.

**Comment by zengchen1024** [comment]
@niuzhenguo This pr depends on #32, because it needs to pass all the acceptance test cases. I will refresh this pr, if #32 is merged.

**Comment by niuzhenguo** [comment]
if so, maybe better to mark this as WIP in case it get merged suddenly, which will cause another PR never can get in.

**Comment by niuzhenguo** [comment]
@zengchen1024 the dependent PR has already in, need a rebase here?

**Comment by zengchen1024** [comment]
@niuzhenguo yes, let me rebase this pr first. thanks!

**Comment by zengchen1024** [comment]
@niuzhenguo I have done for the rebase. Could you merge it? thanks!

**Pull request merged**
