### PR TITLE
Update `Makefile` and `.zuul.yaml`

### PR DESCRIPTION
**Pull request by lego963**
Update `make test` cmd.
Remove `vendor` folder excluding.
Remove `darwin arm64` from ignored binaries.

### CODE REVIEW

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by lego963** [comment]
recheck

**Comment by lego963** [comment]
recheck

**Review by outcatcher — APPROVED** [review]

**Comment by lego963** [comment]
recheck

**Comment by lego963** [comment]
recheck

**Review by anton-sidelnikov — APPROVED** [review]

**Pull request merged**
