### PR TITLE
[zuul] rds instance example and graph visualization

### PR DESCRIPTION
**Pull request by anton-sidelnikov**
## Summary of the Pull Request
There is a plan to show changes in PR by adding additional example and terraform infra visualization. 
Need to create Zuul Job for visualization and publishing.
https://github.com/hieven/terraform-visual - visualization tool (CLI mode)

Depends-On: https://github.com/opentelekomcloud-infra/otc-zuul-jobs/pull/225

### CODE REVIEW

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Review by artem-lifshits — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Pull request merged**
