### PR TITLE
Fix fw_rule_v2 update error

### PR DESCRIPTION
**Pull request by zengchen1024**
This pr is synchronized from https://github.com/gator1/terraform-provider-opentelekomcloud/pull/17

TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccFWRuleV2_basic -timeout 240m
=== RUN   TestAccFWRuleV2_basic
--- PASS: TestAccFWRuleV2_basic (60.16s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     60.169s

### CODE REVIEW

**Comment by zengchen1024** [comment]
@cgriggs01 Could you please merge this pr? Thanks very much!

**Review by paultyng — APPROVED** [review]

**Comment by zengchen1024** [comment]
@paultyng Could you merge this pr? Thanks!

**Comment by paultyng** [comment]
Please add acceptance test results here if possible.

**Comment by zengchen1024** [comment]
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccFWRuleV2_basic -timeout 240m
=== RUN   TestAccFWRuleV2_basic
--- PASS: TestAccFWRuleV2_basic (60.16s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     60.169s

**Pull request merged**
