### PR TITLE
[VBS] Fix backup read operation

### PR DESCRIPTION
**Pull request by outcatcher**
## Summary of the Pull Request
Move to `gophertelekomcloud` with opentelekomcloud/gophertelekomcloud#100 fixed

Minor refactoring of VBS backup v2 `description` field validation

## PR Checklist

* [x] Refers to: #843 
* [x] Tests added/passed.
* [x] Schema updated.

### Import
```
=== RUN   TestAccVBSBackupV2_importBasic
--- PASS: TestAccVBSBackupV2_importBasic (333.69s)
PASS

Process finished with exit code 0
```

### Resource

```
=== RUN   TestAccVBSBackupV2_basic
--- PASS: TestAccVBSBackupV2_basic (337.68s)
=== RUN   TestAccVBSBackupV2_timeout
--- PASS: TestAccVBSBackupV2_timeout (334.61s)
PASS

Process finished with exit code 0
```

### CODE REVIEW

**Comment by outcatcher** [comment]
recheck

**Review by lego963 — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Review by lego963 — APPROVED** [review]

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Pull request merged**
