### PR TITLE
Change to use schema.Timeout instead of hardcoding

### PR DESCRIPTION
**Pull request by niuzhenguo**
Affect resources:
* compute_instance_v2
* blockstorage_volume_v2

### CODE REVIEW

**Comment by niuzhenguo** [comment]
@freesky-edward please take a look at this before merge!

**Comment by freesky-edward** [comment]
I find some other places which has hardcoding time too, could you please change them together?  
1. [loadbalancer1](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/35f48847eb06999dad893e2788c3772853d2549b/opentelekomcloud/resource_opentelekomcloud_elb_loadbalancer.go#L131:57)
[loadbalancer2](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/35f48847eb06999dad893e2788c3772853d2549b/opentelekomcloud/resource_opentelekomcloud_elb_loadbalancer.go#L208:57)
[loadbalancer3](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/35f48847eb06999dad893e2788c3772853d2549b/opentelekomcloud/resource_opentelekomcloud_elb_loadbalancer.go#L231:57)
2. [backend](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/35f48847eb06999dad893e2788c3772853d2549b/opentelekomcloud/resource_opentelekomcloud_elb_loadbalancer.go#L131:57)
[backend2](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/35f48847eb06999dad893e2788c3772853d2549b/opentelekomcloud/resource_opentelekomcloud_elb_loadbalancer.go#L131:57)

**Comment by niuzhenguo** [comment]
@freesky-edward done!

**Comment by freesky-edward** [comment]
@niuzhenguo thanks, LGTM

**Pull request merged**
