### PR TITLE
[MODULES] Re-open Switch to Go Modules

### LINKED ISSUE #215: [PROPOSAL] Switch to Go Modules
As part of the preparation for Terraform v0.12, we would like to migrate all providers to use [Go Modules](https://github.com/golang/go/wiki/Modules). We plan to continue checking dependencies into vendor/ to remain compatible with existing tooling/CI for a period of time, however go modules will be used for management. Go Modules is the official solution for the go programming language, we understand some providers might not want this change yet, however we encourage providers to begin looking towards the switch as this is how we will be managing all Go projects in the future. Would maintainers please react with :+1: for support, or :-1: if you wish to have this provider omitted from the first wave of pull requests. If your provider is in support, we would ask that you avoid merging any pull requests that mutate the dependencies while the Go Modules PR is open (in fact a total codefreeze would be even more helpful), otherwise we will need to close that PR and re-run `go mod init`. Once merged, dependencies can be added or updated as follows:

```
$ GO111MODULE=on go get github.com/some/module@master
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

GO111MODULE=on might be unnecessary depending on your environment, this example will fetch a module @ master and record it in your project's go.mod and go.sum files. It's a good idea to tidy up afterward and then copy the dependencies into vendor/. To remove dependencies from your project, simply remove all usage from your codebase and run:

```
$ GO111MODULE=on go mody tidy
$ GO111MODULE=on go mod vendor
```

Thank you sincerely for all your time, contributions, and cooperation!

### PR DESCRIPTION
**Pull request by appilon**
Closes #215

### CODE REVIEW

**Review by radeksimko — APPROVED** [review]
- `go mod tidy` is no-op
- `go mod vendor` is no-op
- `go.mod` looks reasonable

LGTM, but pending acceptance tests, which I just kicked off. They might take about 10 hours to finish, so I will take a look tomorrow morning.

**Review by radeksimko — CHANGES_REQUESTED** [review]
It looks like the last test run is surfacing some tech debt which needs addressing:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccCCEClusterV3DataSource_basic

------- Stderr: -------
panic: interface conversion: interface {} is nil, not string

goroutine 972 [running]:
github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud.dataSourceCCEClusterV3Read(0xc0004531f0, 0x127e1c0, 0xc0001102c0, 0xc0004531f0, 0x0)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud/data_source_opentelekomcloud_cce_cluster_v3.go:95 +0xdcd
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc0002e9c00, 0xc00024f680, 0x127e1c0, 0xc0001102c0, 0xc00037b198, 0xc0003cfa01, 0xc00022d1f0)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:290 +0x88
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000390000, 0xc0003da500, 0xc00024f680, 0x0, 0x30, 0xc000640000)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x92
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.(*EvalReadDataApply).Eval(0xc00024f2e0, 0x14a6d80, 0xc00037ba00, 0x2, 0x2, 0x128cdc6, 0x4)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/eval_read_data.go:122 +0xf9
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x1490c40, 0xc00024f2e0, 0x14a6d80, 0xc00037ba00, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc00024f300, 0x14a6d80, 0xc00037ba00, 0x2, 0x2, 0x128cdc6, 0x4)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x9c
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.EvalRaw(0x1490d40, 0xc00024f300, 0x14a6d80, 0xc00037ba00, 0x10ead40, 0x1f717e5, 0x10a7360, 0xc000046e40)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/eval.go:53 +0x156
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.Eval(0x1490d40, 0xc00024f300, 0x14a6d80, 0xc00037ba00, 0xc00024f300, 0x1490d40, 0xc00024f300, 0x1308d70)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x123dd20, 0xc00000e5f8, 0x0, 0x0)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/terraform/graph.go:126 +0xc45
github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000452460, 0x123dd20, 0xc00000e5f8, 0xc00061e400)
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/dag/walk.go:387 +0x367
created by github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/teamcity-agent/work/907821a0092b6430/src/github.com/terraform-providers/terraform-provider-opentelekomcloud/vendor/github.com/hashicorp/terraform/dag/walk.go:310 +0x986
```

```
$ grep -R 'd.Get("id")' ./opentelekomcloud/*
./opentelekomcloud/data_source_opentelekomcloud_cce_cluster_v3.go:		ID:    d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_compute_bms_flavor_v2.go:		ID:      d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_compute_bms_nic_v2.go:		ID:     d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_compute_bms_server_v2.go:		ID:         d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_csbs_backup_policy_v1.go:		ID:     d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_csbs_backup_v1.go:		ID:           d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_deh_host_v1.go:		ID:    d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_rts_software_config_v1.go:		Id:   d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_rts_software_deployment_v1.go:		Id:       d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_sfs_file_system_v2.go:		ID:     d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_vbs_backup_policy_v2.go:	policyID := d.Get("id").(string)
./opentelekomcloud/data_source_opentelekomcloud_vbs_backup_v2.go:		Id:         d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_vpc_peering_connection_v2.go:		ID:         d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_vpc_route_v2.go:		RouteID:     d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_vpc_subnet_v1.go:		ID:               d.Get("id").(string),
./opentelekomcloud/data_source_opentelekomcloud_vpc_v1.go:		ID:     d.Get("id").(string),
```
^ I think all of these will need to be changed to `d.Id()`.

**Comment by niuzhenguo** [comment]
Any update here? Should we still have to avoid merging dependencies changes until this get in?

**Comment by appilon** [comment]
I will try and get to this today

**Review by niuzhenguo — APPROVED** [review]
LGTM

**Comment by appilon** [comment]
Unfortunately there are some failing tests I will try and work through them

**Pull request merged**
