### PR TITLE
Bump go version to 1.20

### PR DESCRIPTION
**Pull request by artem-lifshits**
## Summary of the Pull Request
Change go version to v1.20

### CODE REVIEW

**Comment by artem-lifshits** [comment]
Recheck

**Comment by artem-lifshits** [comment]
Recheck

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by artem-lifshits** [comment]
recheck

**Comment by artem-lifshits** [comment]
recheck

**Comment by artem-lifshits** [comment]
Recheck

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by artem-lifshits** [comment]
Regate

**Pull request merged**
