### PR TITLE
[VPCEP]: dependency update

### PR DESCRIPTION
**Pull request by artem-lifshits**
## Summary of the Pull Request
``go.sum`` and ``go.mod`` dependency update after ``gophertelekomcloud`` change.

## PR Checklist

* [x] Refers to: #1940
* [x] Tests passed.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestEndpoint_basic
=== PAUSE TestEndpoint_basic
=== CONT  TestEndpoint_basic
--- PASS: TestEndpoint_basic (64.99s)
=== RUN   TestEndpoint_import
=== PAUSE TestEndpoint_import
=== CONT  TestEndpoint_import
--- PASS: TestEndpoint_import (72.33s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

**Review by anton-sidelnikov — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Comment by simonszu** [comment]
Would it be possible to release that quite soon as a bugfix release? This is currently a blocker for our project, and the projected release date of 1.31.4 is in a week at soonest.

**Comment by Aloento** [comment]
@simonszu OK

**Comment by Aloento** [comment]
@simonszu 
`go get github.com/opentelekomcloud/terraform-provider-opentelekomcloud@355d86626931c3ed034d0996260825fec43b978e`
A new release will be coming soon.

**Comment by simonszu** [comment]
I don't think i can reference directly to a commit hash in a Terraform provider config, but i'll check

**Comment by artem-lifshits** [comment]
Hello @simonszu new provider version with fix was released (v1.31.4), please check.

**Comment by simonszu** [comment]
Yes, it's working for me now. Thank you very much.

**Pull request merged**
