### PR TITLE
Fixes unexpected router region update error

### PR DESCRIPTION
**Pull request by zengchen1024**
this pr is synchronized from https://github.com/gator1/terraform-provider-opentelekomcloud/pull/16

TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccNetworkingV2Router_basic -timeout 240m
=== RUN TestAccNetworkingV2Router_basic
--- PASS: TestAccNetworkingV2Router_basic (77.17s)
PASS
ok github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud 77.174s

### CODE REVIEW

**Comment by zengchen1024** [comment]
@cgriggs01 Could you please merge this pr? Thanks very much!

**Review by paultyng — APPROVED** [review]

**Comment by zengchen1024** [comment]
@paultyng Could you merge this pr? Thanks!

**Comment by paultyng** [comment]
Can you post a snippet of the relevant acceptance testing logs in here? Sorry I should have asked for that the previous time, but I cannot run the tests myself. I think we will be in touch to setup testing internally as well to speed this up.

**Comment by zengchen1024** [comment]
TF_ACC=1 go test ./opentelekomcloud/ -v -run=TestAccNetworkingV2Router_basic -timeout 240m
=== RUN   TestAccNetworkingV2Router_basic
--- PASS: TestAccNetworkingV2Router_basic (77.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-opentelekomcloud/opentelekomcloud     77.174s

**Comment by zengchen1024** [comment]
@paultyng Really appreciate your help! Do you have any other ways for me to contact with you, like slack etc. I can help if you want to setup testing environment.

**Comment by paultyng** [comment]
I believe someone from HashiCorp is reaching out already to setup some communication, I'll keep an eye on my end to make sure it keeps moving, I agree would be easier to just do this via Slack and get your help setting up the acc tests for us to run.

**Pull request merged**
