### PR TITLE
[CCE] Add missing `KMS` config of system volume

### PR DESCRIPTION
**Pull request by r-ising**
## Encryption on system volume

I added the kms id on system volume / root volume.

## PR Checklist

* [X] Refers to: #1813
* [X] Tests added.
* [X] Documentation updated.
* [X] Schema updated.
* [X] Release notes added.

### CODE REVIEW

**Comment by anton-sidelnikov** [comment]
@r-ising Hi, please add release note https://docs.openstack.org/reno/latest/

**Comment by r-ising** [comment]
> @r-ising Hi, please add release note https://docs.openstack.org/reno/latest/

Sorry, i forgot to add this file to git, now it should be there.

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by artem-lifshits — DISMISSED** [review]

**Review by vladimirvshivkov — CHANGES_REQUESTED** [review]
test pass needed

**Comment by r-ising** [comment]
@vladimirvshivkov i fixed the tests

```
2022/07/19 10:59:02 [INFO] Building Swift S3 auth structure
2022/07/19 10:59:02 [INFO] Setting AWS metadata API timeout to 100ms
2022/07/19 10:59:03 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2022/07/19 10:59:03 [INFO] Swift S3 Auth provider used: "StaticProvider"
=== RUN   TestAccCCENodesV3EncryptedVolume
=== PAUSE TestAccCCENodesV3EncryptedVolume
=== CONT  TestAccCCENodesV3EncryptedVolume
    resource_opentelekomcloud_cce_node_v3_test.go:304: Cluster is required by the test. 1 test(s) are using cluster.
    cluster.go:49: starting creating shared cluster
2022/07/19 10:59:09 [DEBUG] Waiting for state to become: [Available]
2022/07/19 10:59:14 [TRACE] Waiting 3s before next try
2022/07/19 10:59:17 [TRACE] Waiting 6s before next try
2022/07/19 10:59:23 [TRACE] Waiting 10s before next try
2022/07/19 10:59:33 [TRACE] Waiting 10s before next try
2022/07/19 10:59:44 [TRACE] Waiting 10s before next try
2022/07/19 10:59:54 [TRACE] Waiting 10s before next try
2022/07/19 11:00:04 [TRACE] Waiting 10s before next try
2022/07/19 11:00:14 [TRACE] Waiting 10s before next try
2022/07/19 11:00:24 [TRACE] Waiting 10s before next try
2022/07/19 11:00:34 [TRACE] Waiting 10s before next try
2022/07/19 11:00:45 [TRACE] Waiting 10s before next try
2022/07/19 11:00:55 [TRACE] Waiting 10s before next try
2022/07/19 11:01:05 [TRACE] Waiting 10s before next try
2022/07/19 11:01:15 [TRACE] Waiting 10s before next try
2022/07/19 11:01:25 [TRACE] Waiting 10s before next try
2022/07/19 11:01:35 [TRACE] Waiting 10s before next try
2022/07/19 11:01:46 [TRACE] Waiting 10s before next try
2022/07/19 11:01:56 [TRACE] Waiting 10s before next try
2022/07/19 11:02:06 [TRACE] Waiting 10s before next try
2022/07/19 11:02:16 [TRACE] Waiting 10s before next try
2022/07/19 11:02:26 [TRACE] Waiting 10s before next try
2022/07/19 11:02:36 [TRACE] Waiting 10s before next try
2022/07/19 11:02:46 [TRACE] Waiting 10s before next try
2022/07/19 11:02:57 [TRACE] Waiting 10s before next try
2022/07/19 11:03:07 [TRACE] Waiting 10s before next try
2022/07/19 11:03:17 [TRACE] Waiting 10s before next try
2022/07/19 11:03:27 [TRACE] Waiting 10s before next try
2022/07/19 11:03:37 [TRACE] Waiting 10s before next try
2022/07/19 11:03:47 [TRACE] Waiting 10s before next try
2022/07/19 11:03:58 [TRACE] Waiting 10s before next try
2022/07/19 11:04:08 [TRACE] Waiting 10s before next try
2022/07/19 11:04:18 [TRACE] Waiting 10s before next try
    cluster.go:137: Cluster usage is 0 now, ready to delete the cluster
    cluster.go:100: starting deleting shared cluster
--- PASS: TestAccCCENodesV3EncryptedVolume (809.12s)
PASS
```


```
2022/07/19 11:29:25 [INFO] Building Swift S3 auth structure
2022/07/19 11:29:25 [INFO] Setting AWS metadata API timeout to 100ms
2022/07/19 11:29:27 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2022/07/19 11:29:27 [INFO] Swift S3 Auth provider used: "StaticProvider"
=== RUN   TestAccCCENodePoolsV3EncryptedVolume
=== PAUSE TestAccCCENodePoolsV3EncryptedVolume
=== CONT  TestAccCCENodePoolsV3EncryptedVolume
    resource_opentelekomcloud_cce_node_pool_v3_test.go:129: Cluster is required by the test. 1 test(s) are using cluster.
    cluster.go:49: starting creating shared cluster
2022/07/19 11:29:33 [DEBUG] Waiting for state to become: [Available]
2022/07/19 11:29:38 [TRACE] Waiting 3s before next try
2022/07/19 11:29:41 [TRACE] Waiting 6s before next try
2022/07/19 11:29:47 [TRACE] Waiting 10s before next try
2022/07/19 11:29:57 [TRACE] Waiting 10s before next try
2022/07/19 11:30:08 [TRACE] Waiting 10s before next try
2022/07/19 11:30:18 [TRACE] Waiting 10s before next try
2022/07/19 11:30:28 [TRACE] Waiting 10s before next try
2022/07/19 11:30:38 [TRACE] Waiting 10s before next try
2022/07/19 11:30:48 [TRACE] Waiting 10s before next try
2022/07/19 11:30:59 [TRACE] Waiting 10s before next try
2022/07/19 11:31:09 [TRACE] Waiting 10s before next try
2022/07/19 11:31:19 [TRACE] Waiting 10s before next try
2022/07/19 11:31:29 [TRACE] Waiting 10s before next try
2022/07/19 11:31:39 [TRACE] Waiting 10s before next try
2022/07/19 11:31:50 [TRACE] Waiting 10s before next try
2022/07/19 11:32:00 [TRACE] Waiting 10s before next try
2022/07/19 11:32:10 [TRACE] Waiting 10s before next try
2022/07/19 11:32:20 [TRACE] Waiting 10s before next try
2022/07/19 11:32:31 [TRACE] Waiting 10s before next try
2022/07/19 11:32:41 [TRACE] Waiting 10s before next try
2022/07/19 11:32:51 [TRACE] Waiting 10s before next try
2022/07/19 11:33:01 [TRACE] Waiting 10s before next try
2022/07/19 11:33:11 [TRACE] Waiting 10s before next try
2022/07/19 11:33:21 [TRACE] Waiting 10s before next try
2022/07/19 11:33:32 [TRACE] Waiting 10s before next try
2022/07/19 11:33:42 [TRACE] Waiting 10s before next try
2022/07/19 11:33:52 [TRACE] Waiting 10s before next try
2022/07/19 11:34:02 [TRACE] Waiting 10s before next try
2022/07/19 11:34:12 [TRACE] Waiting 10s before next try
2022/07/19 11:34:22 [TRACE] Waiting 10s before next try
2022/07/19 11:34:33 [TRACE] Waiting 10s before next try
    cluster.go:137: Cluster usage is 0 now, ready to delete the cluster
    cluster.go:100: starting deleting shared cluster
--- PASS: TestAccCCENodePoolsV3EncryptedVolume (908.83s)
PASS
```

**Review by vladimirvshivkov — APPROVED** [review]

**Comment by anton-sidelnikov** [comment]
Will be merged in #1827

**Pull request closed without merging**
