### PR TITLE
[VPN] psk documentation and validation updates in `resource/vpnaas_site_connection_v2`

### PR DESCRIPTION
**Pull request by jrod-97**
## Summary of the Pull Request
I've updated the description of vpnaas_site_connection_v2 to reflect the real world requirements that are present for the PSK after I ran into some issues trying "any string" that was not accepted.

## PR Checklist

* [ ] Refers to: #xxx
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [ ] Release notes added.

### CODE REVIEW

**Review by vladimirvshivkov — DISMISSED** [review]
I suppose it is a good idea to make this clear.

**Comment by anton-sidelnikov** [comment]
@jrod-97 According the documentation you partly right: "A PSK can contain 6 to 128 characters. Spaces and question marks (?) are not allowed in a PSK. The PSK cannot contain only asterisks (*)"

**Comment by jrod-97** [comment]
I've based my description on the popup in the web covering that appears when trying to paste a psk with a question mark in it. It says: `Spaces and the following special characters are not allowed: <>&?*'"`
Then you need to update the docs of both to clarify. 

The error message that is delivered via the API could also be improved. I got: `The PSK \"?\" is invalid`. And I was left wondering why my nice PSK is transmitted as `?` and suspected a API error at first.

**Comment by anton-sidelnikov** [comment]
@jrod-97 
Yes, thank you, I will forward this to backend team. Also little bit rephrased doc. Added validation.

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by jrod-97** [comment]
The regex to validate is a nice addition. Should improve UX even more.
Thanks for forwarding to the backend team!

**Review by artem-lifshits — APPROVED** [review]

**Review by Aloento — APPROVED** [review]

**Pull request merged**
