### PR TITLE
Fixes unexpected change of region in opentelekomcloud_networking_rout…

### PR DESCRIPTION
**Pull request by niuzhenguo**
This PR tries to fix a issue which has been addressed on openstack provider

### CODE REVIEW

**Comment by niuzhenguo** [comment]
cc @gator1

**Comment by gator1** [comment]
master branch is in use by customers. All pull request needs to go to Integration branch.

**Comment by gator1** [comment]
Please no pull request here actually. All pull requests go to gator1 github and that's the beta.

**Comment by niuzhenguo** [comment]
@gator1 ok, will add a PR there。

**Pull request closed without merging**
