### PR TITLE
Add zuul integration

### PR DESCRIPTION
**Pull request by gtema**

### CODE REVIEW

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Review by outcatcher — APPROVED** [review]

**Comment by gtema** [comment]
regate

**Pull request merged**
