### PR TITLE
Least amount of KMS roles for server_side_encryption

### PR DESCRIPTION
**Pull request by dombisza**
## Summary of the Pull Request
Hello there,

It took me some time to figure out what is the least amount of roles needed to use an encrypted bucket with an OTC user. Thought I would share it with the community. If there is a better place for this, please point me to that direction.

## PR Checklist

* [ ] Refers to: #xxx
* [ ] Tests added/passed.
* [x] Documentation updated.
* [ ] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

### CODE REVIEW

**Comment by artem-lifshits** [comment]
@dombisza great work, thank you! Please use `make tffmtfix` for formatting and we will approve the PR

**Comment by dombisza** [comment]
@artem-lifshits thanks! I ran `make tffmtfix` , but it did not change any of the formatting:
```bash
❯ make tffmtfix >/dev/null && echo OK || echo NOK ; git status
OK
On branch devel
Your branch is up to date with 'origin/devel'.

nothing to commit, working tree clean
```

**Comment by anton-sidelnikov** [comment]
@dombisza hi, please give us permission to push into your fork

**Comment by dombisza** [comment]
@anton-sidelnikov  Allow edits by maintainers was turned on already, but I added you guys to my fork.

**Comment by anton-sidelnikov** [comment]
> @anton-sidelnikov Allow edits by maintainers was turned on already, but I added you guys to my fork.

@dombisza Great thanks! Now everything should pass

**Review by anton-sidelnikov — APPROVED** [review]

**Review by artem-lifshits — APPROVED** [review]

**Pull request merged**
